# Jekyll configuration

name: AKABE
description: プログラミングとか機械学習とかの覚書

# url is currently only used only for the RSS feed in feed.xml
url: http://akabe.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl:

github: 'akabe'
twitter: 'ackey_65535'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: 'UA-58142361-1'

permalink: /:year/:month/:title
paginate: 3

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
