# Site settings
title: Alpha Beta Epsilon
email:
description: プログラミングの覚書

baseurl: ''
url: 'http://akabe.github.io'

# Your accounts:
twitter_username: 'ackey_65535'
github_username:  'akabe'
qiita_username: 'akabe'
gaaccount: 'UA-58142361-1'

permalink: /:year/:month/:title
gems: [jekyll-paginate]
paginate: 5

markdown: kramdown
